apiVersion: apps/v1
kind: Deployment
metadata:
  name: singlespa-json
  labels:
    app: singlespa-js
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: singlespa-js
    
  template:
    metadata:
      name: singlespa-js
      labels:
        app: singlespa-js
    spec:
      containers:
        - name: singlespa-json
          image: ghcr.io/sreenidhize/db:123
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets: 
        - name: mysecret

---
apiVersion: v1
kind: Service
metadata:
  name: singlespa-json
  labels:
    app: singlespa-js
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: singlespa-js